### ISSUE TITLE
Need to update build.gradle

### ISSUE THREAD

**Issue by ShreiderWalter** [dapetcu21/defold-apkx#1]
When using current version of apkx extension it overrides android dependencies as the build.gradle file is empty. It causes the impossibility to bundle android build when using some other extensions (for example push-extension).
I believe that proper dependencies list in build.gradle should be next:
dependencies {
  compile 'com.android.support:support-v4:26.+'
}
Could you please make it asap? Or grant me rights to make a pull request please

**Comment by dapetcu21** [comment]
It's a public project under the Apache 2.0 license. You have the rights to fork it, fix the issue, then submit a pull request back to this repo at your leisure. 

As I said on [defold/extension-push#23](https://github.com/defold/extension-push/issues/23), once I get the time to catch up with maintenance, if you submit a PR, I'll happily test it and merge it. Until then, you can use your fixed fork as a dependency URL for your game.

**Comment by britzl** [comment]
@ShreiderWalter How to fork a GitHub repository: https://docs.github.com/en/github/getting-started-with-github/fork-a-repo
